import type { Metadata } from 'next';
import StoreProvider from "@src/stores/StoreProvider";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <StoreProvider>
        {children}
        </StoreProvider>
      </body>
    </html>
  )
}
